[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
on_chain = "6BbPLThKL7envn7y3TkouLuBqF6qQiXvgLDFFyKzdCM9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
