[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
tokio = "1.38.0"
anchor-client = "0.28.0"
blockroot = { path = "../blockroot", features = ["no-entrypoint"]}
